version: '3'

services:
  pushetta:
    container_name: pushetta-be
    build:
      context: .
    expose:
      - 8001
    ports:
      - 8001:8001
    depends_on:
      - db
      - redis
      - elastic
      - rabbit
    env_file:
      - ./pushetta.env
    volumes:
      - ./volumes/pushetta:/usr/share/pushetta/

  db:
    image: mysql:5.5
    container_name: db
    ports:
      - 3306:3306
    expose:
      - 3306
    env_file:
      - ./database.env
    volumes:
      - ./volumes/database/:/var/lib/mysql/

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    expose:
      - 5672
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - ./rabbit.env

  elastic:
    image: elasticsearch:2
    container_name: elastic
    ports:
      - '9200:9200'
    expose:
      - 9200
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    cap_add:
      - IPC_LOCK
    volumes:
      - ./volumes/elasticsearch:/usr/share/elasticsearch/data

  redis:
    image: redis:4.0-alpine
    container_name: redis
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - ./volumes/redis:/data

  mosquitto:
    image: guglielmino/mosquitto-pushetta-auth-plugin:v1.0.9
    container_name: mosquitto
    ports:
      - 1883:1883
    expose:
      - 1883
    depends_on:
      - db
    command:
      ['/wait_for', 'db:3306', '--', '/usr/sbin/mosquitto', '-c', '/etc/mosquitto/mosquitto.conf']
